//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Literals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ramses.App_LocalResources.Literals", typeof(Literals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletar.
        /// </summary>
        public static string btn_delete {
            get {
                return ResourceManager.GetString("btn_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string btn_edit {
            get {
                return ResourceManager.GetString("btn_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string btn_exit {
            get {
                return ResourceManager.GetString("btn_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string btn_no {
            get {
                return ResourceManager.GetString("btn_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string btn_yes {
            get {
                return ResourceManager.GetString("btn_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tudo.
        /// </summary>
        public static string lbl_all {
            get {
                return ResourceManager.GetString("lbl_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outros Campos.
        /// </summary>
        public static string lbl_another_fields {
            get {
                return ResourceManager.GetString("lbl_another_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condição.
        /// </summary>
        public static string lbl_condition {
            get {
                return ResourceManager.GetString("lbl_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partido Eleitoral.
        /// </summary>
        public static string lbl_electoral_party {
            get {
                return ResourceManager.GetString("lbl_electoral_party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eleitos por UF.
        /// </summary>
        public static string lbl_grafico1_subtitulo {
            get {
                return ResourceManager.GetString("lbl_grafico1_subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deputados.
        /// </summary>
        public static string lbl_grafico1_titulo {
            get {
                return ResourceManager.GetString("lbl_grafico1_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string lbl_name {
            get {
                return ResourceManager.GetString("lbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profissão.
        /// </summary>
        public static string lbl_profession {
            get {
                return ResourceManager.GetString("lbl_profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        public static string lbl_situation {
            get {
                return ResourceManager.GetString("lbl_situation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string lbl_state {
            get {
                return ResourceManager.GetString("lbl_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soma.
        /// </summary>
        public static string lbl_sum {
            get {
                return ResourceManager.GetString("lbl_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string lbl_value {
            get {
                return ResourceManager.GetString("lbl_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro no sistema, onde já detectamos o erro e estamos trabalhando para corrigi-lo. Quando o erro for corrigido você será comunicado. Pedimos desculpas pelo transtorno..
        /// </summary>
        public static string msg_internal_error {
            get {
                return ResourceManager.GetString("msg_internal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O carregamento foi realizado com sucesso..
        /// </summary>
        public static string msg_load_action {
            get {
                return ResourceManager.GetString("msg_load_action", resourceCulture);
            }
        }
    }
}
