//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Ramses.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RamsesDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RamsesDBEntities object using the connection string found in the 'RamsesDBEntities' section of the application configuration file.
        /// </summary>
        public RamsesDBEntities() : base("name=RamsesDBEntities", "RamsesDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RamsesDBEntities object.
        /// </summary>
        public RamsesDBEntities(string connectionString) : base(connectionString, "RamsesDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RamsesDBEntities object.
        /// </summary>
        public RamsesDBEntities(EntityConnection connection) : base(connection, "RamsesDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Deputado> Deputados
        {
            get
            {
                if ((_Deputados == null))
                {
                    _Deputados = base.CreateObjectSet<Deputado>("Deputados");
                }
                return _Deputados;
            }
        }
        private ObjectSet<Deputado> _Deputados;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Deputados EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDeputados(Deputado deputado)
        {
            base.AddObject("Deputados", deputado);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RamsesDBModel", Name="Deputado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Deputado : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Deputado object.
        /// </summary>
        /// <param name="ideCadastro">Initial value of the ideCadastro property.</param>
        public static Deputado CreateDeputado(global::System.String ideCadastro)
        {
            Deputado deputado = new Deputado();
            deputado.ideCadastro = ideCadastro;
            return deputado;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ideCadastro
        {
            get
            {
                return _ideCadastro;
            }
            set
            {
                if (_ideCadastro != value)
                {
                    OnideCadastroChanging(value);
                    ReportPropertyChanging("ideCadastro");
                    _ideCadastro = StructuralObject.SetValidValue(value, false, "ideCadastro");
                    ReportPropertyChanged("ideCadastro");
                    OnideCadastroChanged();
                }
            }
        }
        private global::System.String _ideCadastro;
        partial void OnideCadastroChanging(global::System.String value);
        partial void OnideCadastroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numLegislatura
        {
            get
            {
                return _numLegislatura;
            }
            set
            {
                OnnumLegislaturaChanging(value);
                ReportPropertyChanging("numLegislatura");
                _numLegislatura = StructuralObject.SetValidValue(value, true, "numLegislatura");
                ReportPropertyChanged("numLegislatura");
                OnnumLegislaturaChanged();
            }
        }
        private global::System.String _numLegislatura;
        partial void OnnumLegislaturaChanging(global::System.String value);
        partial void OnnumLegislaturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nomeParlamentar
        {
            get
            {
                return _nomeParlamentar;
            }
            set
            {
                OnnomeParlamentarChanging(value);
                ReportPropertyChanging("nomeParlamentar");
                _nomeParlamentar = StructuralObject.SetValidValue(value, true, "nomeParlamentar");
                ReportPropertyChanged("nomeParlamentar");
                OnnomeParlamentarChanged();
            }
        }
        private global::System.String _nomeParlamentar;
        partial void OnnomeParlamentarChanging(global::System.String value);
        partial void OnnomeParlamentarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sexo
        {
            get
            {
                return _Sexo;
            }
            set
            {
                OnSexoChanging(value);
                ReportPropertyChanging("Sexo");
                _Sexo = StructuralObject.SetValidValue(value, true, "Sexo");
                ReportPropertyChanged("Sexo");
                OnSexoChanged();
            }
        }
        private global::System.String _Sexo;
        partial void OnSexoChanging(global::System.String value);
        partial void OnSexoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Profissao
        {
            get
            {
                return _Profissao;
            }
            set
            {
                OnProfissaoChanging(value);
                ReportPropertyChanging("Profissao");
                _Profissao = StructuralObject.SetValidValue(value, true, "Profissao");
                ReportPropertyChanged("Profissao");
                OnProfissaoChanged();
            }
        }
        private global::System.String _Profissao;
        partial void OnProfissaoChanging(global::System.String value);
        partial void OnProfissaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LegendaPartidoEleito
        {
            get
            {
                return _LegendaPartidoEleito;
            }
            set
            {
                OnLegendaPartidoEleitoChanging(value);
                ReportPropertyChanging("LegendaPartidoEleito");
                _LegendaPartidoEleito = StructuralObject.SetValidValue(value, true, "LegendaPartidoEleito");
                ReportPropertyChanged("LegendaPartidoEleito");
                OnLegendaPartidoEleitoChanged();
            }
        }
        private global::System.String _LegendaPartidoEleito;
        partial void OnLegendaPartidoEleitoChanging(global::System.String value);
        partial void OnLegendaPartidoEleitoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UFEleito
        {
            get
            {
                return _UFEleito;
            }
            set
            {
                OnUFEleitoChanging(value);
                ReportPropertyChanging("UFEleito");
                _UFEleito = StructuralObject.SetValidValue(value, true, "UFEleito");
                ReportPropertyChanged("UFEleito");
                OnUFEleitoChanged();
            }
        }
        private global::System.String _UFEleito;
        partial void OnUFEleitoChanging(global::System.String value);
        partial void OnUFEleitoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Condicao
        {
            get
            {
                return _Condicao;
            }
            set
            {
                OnCondicaoChanging(value);
                ReportPropertyChanging("Condicao");
                _Condicao = StructuralObject.SetValidValue(value, true, "Condicao");
                ReportPropertyChanged("Condicao");
                OnCondicaoChanged();
            }
        }
        private global::System.String _Condicao;
        partial void OnCondicaoChanging(global::System.String value);
        partial void OnCondicaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SiTuacaoMandato
        {
            get
            {
                return _SiTuacaoMandato;
            }
            set
            {
                OnSiTuacaoMandatoChanging(value);
                ReportPropertyChanging("SiTuacaoMandato");
                _SiTuacaoMandato = StructuralObject.SetValidValue(value, true, "SiTuacaoMandato");
                ReportPropertyChanged("SiTuacaoMandato");
                OnSiTuacaoMandatoChanged();
            }
        }
        private global::System.String _SiTuacaoMandato;
        partial void OnSiTuacaoMandatoChanging(global::System.String value);
        partial void OnSiTuacaoMandatoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Matricula
        {
            get
            {
                return _Matricula;
            }
            set
            {
                OnMatriculaChanging(value);
                ReportPropertyChanging("Matricula");
                _Matricula = StructuralObject.SetValidValue(value, true, "Matricula");
                ReportPropertyChanged("Matricula");
                OnMatriculaChanged();
            }
        }
        private global::System.String _Matricula;
        partial void OnMatriculaChanging(global::System.String value);
        partial void OnMatriculaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gabinete
        {
            get
            {
                return _Gabinete;
            }
            set
            {
                OnGabineteChanging(value);
                ReportPropertyChanging("Gabinete");
                _Gabinete = StructuralObject.SetValidValue(value, true, "Gabinete");
                ReportPropertyChanged("Gabinete");
                OnGabineteChanged();
            }
        }
        private global::System.String _Gabinete;
        partial void OnGabineteChanging(global::System.String value);
        partial void OnGabineteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Anexo
        {
            get
            {
                return _Anexo;
            }
            set
            {
                OnAnexoChanging(value);
                ReportPropertyChanging("Anexo");
                _Anexo = StructuralObject.SetValidValue(value, true, "Anexo");
                ReportPropertyChanged("Anexo");
                OnAnexoChanged();
            }
        }
        private global::System.String _Anexo;
        partial void OnAnexoChanging(global::System.String value);
        partial void OnAnexoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fone
        {
            get
            {
                return _Fone;
            }
            set
            {
                OnFoneChanging(value);
                ReportPropertyChanging("Fone");
                _Fone = StructuralObject.SetValidValue(value, true, "Fone");
                ReportPropertyChanged("Fone");
                OnFoneChanged();
            }
        }
        private global::System.String _Fone;
        partial void OnFoneChanging(global::System.String value);
        partial void OnFoneChanged();

        #endregion

    }

    #endregion

}
